site_name: DataHub
site_description: DataHub is a web service for hosting datapackages.
repo_url: https://github.com/datahq/docs
extra_css:
    - css/marmaid.css
    - css/main.css
extra_javascript:
    - js/mermaid.min.js
pages:
- Home: 'index.md'
- Developers:
  - 'Getting started': developers/index.md
  - Platform: developers/platform.md
  - Deploy: developers/deploy.md
  - API: developers/api.md
  - Publish: developers/publish.md
  - Views: developers/views.md
  - Views Research: developers/views-research.md
  - User Stories: developers/user-stories.md
- Publishers:
  - 'Getting started': publishers/index.md
  - 'Core Datasets': publishers/core-datasets.md
  - 'Core Data Curators': publishers/core-data-curators.md
  - CLI: publishers/cli.md
  - Views: publishers/views.md
theme: readthedocs
markdown_extensions:
  - pymdownx.github
  - fontawesome_markdown
